# The FROM instruction sets the Base Image for subsequent instructions.
# Using Nginx as Base Image
FROM registry.cn-beijing.aliyuncs.com/boheyayi/nodeimg:v2.0
MAINTAINER king <87287864@qq.com>


# The RUN instruction will execute any commands
# Adding HelloWorld page into Nginx server
COPY . /root

WORKDIR /root

RUN sed -i "s/^.*start:main.*$/    \"start:main\": \"export NODE_ENV=production; pm2  start  \.\/build\/server\.js -i 2 --no-daemon \",/g" package.json

RUN npm config set registry https://registry.npm.taobao.org

RUN npm install antd-mobile@1.1.3 --save

RUN npm install svg-sprite-loader@0.3.1 -D

RUN npm install babel-plugin-import --save-dev

RUN npm install jsonwebtoken

RUN npm install webpack

RUN npm run builddev

RUN npm run deploy

COPY ./rem.js ./build

COPY ./qiniu.min.js ./build

COPY ./require.js ./build

COPY ./google.js ./build

COPY ./zhugeio.js ./build

# The EXPOSE instruction informs Docker that the container listens on the specified network ports at runtime
EXPOSE 3000

# Ubuntu
RUN echo "Asia/shanghai" > /etc/timezone;
# CentOS
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# The CMD instruction provides default execution command for an container
# Start Nginx and keep it from running background
CMD ["npm", "run", "start:main"]
